### ISSUE TITLE
Plugin cf7 style depends on theme

### ISSUE THREAD

**Issue by Tobias-Conrad** [WPTie/CF7Customizer#12]
Hello Ahmad Awais. @ahmadawais @robertdevore @ahmadbilaldev 
I'm Tobias_Conrad, i think i wrote you a while ago.
Our client has a problem with your plugin usage, and ask us to fix it as far as she could get a response on your plugin support page. We created a new plugin for her, cf7 style do not depend on theme and can be used without changing for every theme installed on site. Also we added separate style settings for each CF7 shortcode.
Tobias/Me is kindly asking you if it is possible to completely replace your plugin and switch ownership for your plugin's page on WP.org to Tobias_Conrad?
Best regards Tobias and Vlad (developer)

**Comment by Tobias-Conrad** [comment]
Developers another point is: If you could look here, a lot of complaints with errors that lead to no submitting of the cf7 https://wordpress.org/support/plugin/cf7-customizer/
So i had to disable your style plugin to get the forms working again.

**Comment by ahmadawais** [comment]
Hey, Tobias!

As I mentioned before, I am not interested in giving up this plugin or its ownership. If you'd like to contribute to the code, please send in a Pull Request. I would love nothing more to see this plugin improved. I'll give the due credit to you folks for the contribution as well.

**Comment by Tobias-Conrad** [comment]
Hey Ahmad,

We decided to not go the way with you if we will not be the owner also.

Best regards Tobias

**Comment by ahmadawais** [comment]
If you want to acquire the plugin, I may think about selling it. But not
giving it away :)

Peace! ✌️

>

**Comment by Tobias-Conrad** [comment]
@ahmadawais We tested your plugin not fully working, it is theme connected, with old code/library, with no support given since months. 
You not sold anything to them and you do not have anything to sell to your audience, so at the moment it is not a bargain. Please give us your paypal email address and we will instantly transfer 200 € to it for changing the complete ownership to Tobias_Conrad.
If you like to receive more, you have to offer more.

**Comment by ahmadawais** [comment]
Your attitude sucks. You know that? You should probably learn to speak more kindly and considerately. If you think I'll sell a plugin with 10k installs, 23k emails subscribers, and custom landing pages with videos for what I charge for an hour of my dev time, you are kidding right. No thanks!

**Comment by Tobias-Conrad** [comment]
Hey Ahmad,

We are sorry to hear that you are not happy with our suggestion. Let us explain: 
Half of your active user are on old versions. Further, concerning your list: I  never got an double opt in email. So we can not write to the users without risking to be not with the law and get fined.
So we would like to know your offer for ownership, pages and list? 400€? We spent a lot of time and money on developing the complete new version. So we are ready to replace our Plugin with yours by changing only the slugs. 

Another option is that we publish our new version independently. But in this case you lose active users. Further, with the current version like it is in conjunction with lack of support you may also loose reputation. 

We offer you to get an outstanding Plugin that allows you to spend no time to support and to the audience anymore. 

We would thank you on the Plugin page and put your reputation back up on building plugins. This deal could be to your advantage. 

Best regards and thank you for your attention. 

Tobias passionated WP user
