### ISSUE TITLE
Search Bar Issue with Twenty Sixteen

### ISSUE THREAD

**Issue by ahmadawais** [WPTie/CF7Customizer#3]
Why was CF7 Customizer affecting Search bar in TwentySixteen theme? Need to look into it.

**Comment by robertdevore** [comment]
I'm not sure if you found out what the issue was, but I was just testing this on the nightly build of WordPress and TwentySixteen and I don't see any errors happening with the search bar.

**Comment by ahmadawais** [comment]
@deviodigital I have addressed them a little, but plan to look into it to see if there is still anything going on. In version, 1.0.1.

**Comment by ahmadawais** [comment]
Fixed! It was an issue in previous version of the theme not this plugin.

**Comment by robertdevore** [comment]
Awesome!
