### ISSUE TITLE
Notice text if CF7 isn't installed says "this theme"

### ISSUE THREAD

**Issue by robertdevore** [WPTie/CF7Customizer#5]
I was installing this plugin to do some testing with it and didn't have CF7 installed, so I got the following message:

![notice](https://cloud.githubusercontent.com/assets/9917957/10423444/a8397b0c-7094-11e5-9bb8-1000b7eaee39.png)

I assume it should say "CF7 Customizer" instead of "this theme".

I'll submit a PR to change the text for you.

**Comment by ahmadawais** [comment]
Thanks for that @deviodigital . Merged the PR.
