### ISSUE TITLE
Theme Conflict

### ISSUE THREAD

**Issue by ahmadawais** [WPTie/CF7Customizer#7]
I just got an email about some theme conflicting with the TGMPA plugin. This issue with be soon addressed. 

```
Fatal error: Cannot redeclare cfc_tgmpa_load_bulk_installer() in file 'class-tgm-plugin-activation.php
```

Looks like my prefix was not enough. What are the odds?

**Comment by ediamin** [comment]
Cannot find any function named `cfc_tgmpa_load_bulk_installer()` in class-tgm-plugin-activation.php. Instead this file has `tgmpa_load_bulk_installer()` and it is inside in a function_exists check. So, the error shouldn't show up. I think you should ask the email sender to send you his/her class-tgm-plugin-activation.php file.

**Comment by ahmadawais** [comment]
@ediamin I figured it out. It was actually `tgmpa_load_bulk_installer()` turns out, the user who sent that email was using a theme or plugin with an outdated version of TGMPA class i.e. both insecure and full of bugs like this. Told him to get the theme author to update dependency class.

I am also thinking to prefix functions in the class file anyway.

**Comment by ediamin** [comment]
I think it is better not to touch the `class-tgm-plugin-activation.php` file. We should use the original library and update whenever its author update this file.

**Comment by ahmadawais** [comment]
@ediamin That's true, but it leaves room for bad user experience just like this. A potential user who wants to use the plugin ends up not using it, just coz the theme he uses has no support anymore. What would you suggest?

**Comment by ediamin** [comment]
This file includes every class and function before checking if its already been loaded or not. So, if we don't touch this file at all and update to the latest, then there should be no error.

**Comment by ahmadawais** [comment]
@ediamin That's true, but the error is not at the end of my plugin. It's someone else's outdated plugin/theme's TGMPA which is breaking my plugin.
